# Generated by Django 3.1.1 on 2020-11-20 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcemnt',
            name='choice',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcemnt',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.grade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcemnt',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
