# Generated by Django 3.1.1 on 2020-11-20 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201120_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcemnt',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='announcemnt',
            name='grade',
        ),
    ]
