# Generated by Django 3.1.1 on 2020-11-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_assigment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigment',
            name='name',
            field=models.FileField(upload_to='media/techer_give_assigment'),
        ),
        migrations.AlterField(
            model_name='submmitted_assigmet',
            name='submitted',
            field=models.FileField(upload_to='media/student_subbmit_assigment'),
        ),
    ]
