# Generated by Django 3.1.1 on 2020-11-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigment',
            name='name',
            field=models.FileField(upload_to='static/give'),
        ),
    ]
