# Generated by Django 3.1.1 on 2020-11-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201118_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigment',
            name='topic',
            field=models.CharField(default='homework', max_length=20),
            preserve_default=False,
        ),
    ]
