# Generated by Django 3.1.1 on 2020-11-21 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201121_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.subject'),
        ),
    ]
